import os
import shutil
import zipfile
import urllib.request
from pathlib import Path
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from auto_readme.analyzer import analyze
from auto_readme.manifest import read_manifest
from auto_readme.sections.usage import build_usage
from auto_readme.sections.installation import build_installation
from auto_readme.sections.api_reference import build_api_reference
from auto_readme.validator import validate
from auto_readme.merger import _wrap_section

app = FastAPI(title="auto-readme API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class GenerateRequest(BaseModel):
    github_url: str

@app.post("/api/generate")
async def generate_readme(req: GenerateRequest):
    url = req.github_url.rstrip("/")
    if "github.com" not in url:
        raise HTTPException(status_code=400, detail="Please enter a valid github.com URL")
    
    # Extract owner and repo
    parts = url.split("github.com/")[-1].split("/")
    if len(parts) < 2:
        raise HTTPException(status_code=400, detail="Invalid GitHub repository URL")
    owner, repo = parts[0], parts[1]
    
    workspace = Path("tmp_workspace")
    workspace.mkdir(exist_ok=True)
    zip_path = workspace / f"{repo}.zip"
    repo_dir = workspace / f"{repo}-main"
    
    try:
        # Try downloading the 'main' branch zip
        zip_url = f"https://github.com/{owner}/{repo}/archive/refs/heads/main.zip"
        try:
            urllib.request.urlretrieve(zip_url, zip_path)
        except urllib.error.HTTPError:
            # Fallback to 'master' branch if main does not exist
            zip_url = f"https://github.com/{owner}/{repo}/archive/refs/heads/master.zip"
            repo_dir = workspace / f"{repo}-master"
            urllib.request.urlretrieve(zip_url, zip_path)
            
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            top_level = zip_ref.namelist()[0].split('/')[0]
            repo_dir = workspace / top_level
            zip_ref.extractall(workspace)
            
        # Run auto-readme pipeline
        manifest = read_manifest(repo_dir)
        # Override manifest name to the repo name if not detected
        if not manifest.name:
            manifest.name = repo
            
        analysis = analyze(repo_dir)
        
        if not analysis.modules and not manifest.cli_scripts:
            return {
                "markdown": f"# {repo}\n\n> This README was generated by auto-readme.\n\n**Warning:** No Python files (`.py`) or entry points were detected in this repository. Ensure this is a Python project and that files are not hidden in tests/ or ignored directories.",
                "repo_name": repo
            }
        
        installation_raw = build_installation(manifest)
        usage_raw = build_usage(analysis, manifest)
        api_raw = build_api_reference(analysis, max_tokens_per_symbol=300)
        
        # Validate LLM output for hallucinations
        usage_res = validate(usage_raw, analysis)
        if usage_res.has_errors:
            errs = "\n".join(str(w) for w in usage_res.warnings if w.level == "error")
            raise HTTPException(status_code=500, detail=f"Validation failed for Usage section:\n{errs}")
            
        api_res = validate(api_raw, analysis)
        if api_res.has_errors:
            errs = "\n".join(str(w) for w in api_res.warnings if w.level == "error")
            raise HTTPException(status_code=500, detail=f"Validation failed for API Reference:\n{errs}")
            
        # Wrap in standard markers
        installation = _wrap_section(installation_raw, "INSTALLATION")
        usage = _wrap_section(usage_raw, "USAGE")
        api_ref = _wrap_section(api_raw, "API")
        
        full_readme = f"# {repo}\n\n> This README was automatically generated by [auto-readme](https://github.com/AagoshRajSri/auto-readme).\n\n{installation}\n{usage}\n{api_ref}"
        
        return {"markdown": full_readme, "repo_name": repo}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if zip_path.exists():
            try:
                zip_path.unlink()
            except OSError as e:
                print(f"Warning: Failed to delete {zip_path}: {e}")
        if repo_dir.exists():
            try:
                shutil.rmtree(repo_dir, ignore_errors=True)
            except OSError as e:
                print(f"Warning: Failed to delete {repo_dir}: {e}")
