import os
import shutil
import zipfile
import urllib.request
from pathlib import Path

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import ReadmeGeneration
from .serializers import ReadmeGenerationSerializer, GenerateReadmeRequestSerializer

from auto_readme.analyzer import analyze
from auto_readme.manifest import read_manifest
from auto_readme.sections.usage import build_usage
from auto_readme.sections.installation import build_installation
from auto_readme.sections.api_reference import build_api_reference
from auto_readme.validator import validate
from auto_readme.merger import wrap_section


def generate_from_github(url: str):
    url = url.rstrip("/")
    if "github.com" not in url:
        raise ValueError("Please enter a valid github.com URL")

    parts = url.split("github.com/")[-1].split("/")
    if len(parts) < 2:
        raise ValueError("Invalid GitHub repository URL")
    owner, repo = parts[0], parts[1]

    workspace = Path("tmp_workspace")
    workspace.mkdir(exist_ok=True)
    zip_path = workspace / f"{repo}.zip"
    repo_dir = workspace / f"{repo}-main"

    try:
        zip_url = f"https://github.com/{owner}/{repo}/archive/refs/heads/main.zip"
        try:
            urllib.request.urlretrieve(zip_url, zip_path)
        except urllib.error.HTTPError:
            zip_url = f"https://github.com/{owner}/{repo}/archive/refs/heads/master.zip"
            repo_dir = workspace / f"{repo}-master"
            urllib.request.urlretrieve(zip_url, zip_path)

        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            top_level = zip_ref.namelist()[0].split('/')[0]
            repo_dir = workspace / top_level
            zip_ref.extractall(workspace)

        manifest = read_manifest(repo_dir)
        if manifest.name == "unknown":
            manifest.name = repo

        analysis = analyze(repo_dir)

        if not analysis.modules and not manifest.cli_scripts:
            full_readme = (
                f"# {repo}\n\n"
                f"> This README was generated by auto-readme.\n\n"
                f"**Warning:** No Python files (`.py`) or entry points were detected in this repository."
            )
            return repo, full_readme

        installation_raw = build_installation(manifest)
        usage_raw = build_usage(analysis, manifest)
        api_raw = build_api_reference(analysis, max_tokens_per_symbol=300)

        usage_res = validate(usage_raw, analysis)
        usage_syntax_errs = [w for w in usage_res.warnings if w.level == "error" and w.check == "syntax"]
        if usage_syntax_errs:
            errs = "\n".join(str(w) for w in usage_syntax_errs)
            raise ValueError(f"Syntax error in Usage section code block:\n{errs}")

        api_res = validate(api_raw, analysis)
        api_syntax_errs = [w for w in api_res.warnings if w.level == "error" and w.check == "syntax"]
        if api_syntax_errs:
            errs = "\n".join(str(w) for w in api_syntax_errs)
            raise ValueError(f"Syntax error in API Reference code block:\n{errs}")

        installation = wrap_section(installation_raw, "INSTALLATION")
        usage = wrap_section(usage_raw, "USAGE")
        api_ref = wrap_section(api_raw, "API")

        lang_badge = "![Python](https://img.shields.io/badge/Python-3.8+-3776AB?style=flat-square&logo=python&logoColor=white)"
        gen_badge = "![auto-readme](https://img.shields.io/badge/docs-auto--readme-black?style=flat-square)"
        full_readme = (
            f"# {repo}\n\n"
            f"{lang_badge} {gen_badge}\n\n"
            f"> **{repo}** — automatically documented by [auto-readme](https://github.com/AagoshRajSri/auto-readme).\n\n"
            f"---\n\n"
            f"{installation}\n{usage}\n{api_ref}"
        )
        return repo, full_readme

    finally:
        if zip_path.exists():
            try:
                zip_path.unlink()
            except OSError:
                pass
        if repo_dir.exists():
            try:
                shutil.rmtree(repo_dir, ignore_errors=True)
            except OSError:
                pass


class GenerateReadmeAPIView(APIView):
    def post(self, request, *args, **kwargs):
        serializer = GenerateReadmeRequestSerializer(data=request.data)
        if serializer.is_valid():
            url = serializer.validated_data['url']
            provider = serializer.validated_data.get('provider', 'gemini')
            
            # Record in database
            generation = ReadmeGeneration.objects.create(
                repo_url=url,
                status='PROCESSING'
            )

            try:
                from auto_readme.llm import set_provider
                set_provider(provider)
                
                repo_name, markdown = generate_from_github(url)
                generation.status = 'COMPLETED'
                generation.generated_markdown = markdown
                generation.save()

                return Response({
                    "id": generation.id,
                    "repo_name": repo_name,
                    "markdown": markdown,
                    "status": "COMPLETED"
                }, status=status.HTTP_200_OK)

            except Exception as e:
                generation.status = 'FAILED'
                generation.save()
                return Response({"detail": str(e)}, status=status.HTTP_400_BAD_REQUEST)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



class ReadmeDetailAPIView(APIView):
    def get(self, request, id, *args, **kwargs):
        try:
            generation = ReadmeGeneration.objects.get(id=id)
            serializer = ReadmeGenerationSerializer(generation)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except ReadmeGeneration.DoesNotExist:
            return Response({"error": "Generation not found."}, status=status.HTTP_404_NOT_FOUND)

